spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inspien_db?serverTimezone=UTC
    username: root
    password: root

# 로컬 SFTP 모킹 환경 (Docker용)
sftp:
  host: localhost
  port: 2222
  user: tester
  password: password
  path: /home/tester/upload